# Support for Circle CI -- https://circleci.com/gh/upx/upx
# Copyright (C) Markus Franz Xaver Johannes Oberhumer

branches:
  only:
    - devel
    - travis

machine:
  environment:
    TRAVIS_OS_NAME: linux
    C: gcc-4.8-m64
    B: release
    CROSS:
    T:

checkout:
  post:
    - git submodule update --init --recursive

dependencies:
  pre:
    - mkdir -p ../deps
    - cd ../deps && wget -q -O - https://github.com/upx/upx/releases/download/v3.00/ucl-1.03.tar.xz | tar -xJ
    - cd ../deps && wget -q -O - https://github.com/upx/upx/releases/download/v3.00/zlib-1.2.8.tar.xz | tar -xJ
    - cd ../deps && git clone https://github.com/upx/upx-testsuite
  override:
    - mkdir -p ../build/travis
    - bash ./.github/travis_build.sh

test:
  override:
    - bash ./.github/travis_testsuite_1.sh

# vim:set ts=2 sw=2 et:
