# Copyright (C) Markus Franz Xaver Johannes Oberhumer
# see https://github.com/crate-ci/typos

name: 'Misc - Spell check'
on:
  schedule: [cron: '55 0 * * 3'] # run weekly Wednesday 00:55 UTC
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  job-spell-check:
    if: github.repository_owner == 'upx'
    name: 'Spell check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with: { submodules: false }
      - name: 'Spell check with crate-ci/typos'
        uses: crate-ci/typos@master
        with: { config: ./.github/typos_config.toml }
